# Change these first
owner: Afra-b # Your GitHub organization or username, where this repository lives
repo: afrab-status-page # The name of this repository

workflowSchedule:
  graphs: "0 0 * * *"
  uptime: "*/5 * * * *"

sites:
  - name: AFRAB's Main website
    url: https://website-three-iota-94.vercel.app/
  - name: AFRAB's API DOCS
    url: https://afrab-dev-api-v1.onrender.com/api/swagger/

status-website:
  # Remove the cname line since you're using GitHub Pages
  baseUrl: /afrab-status-page
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: AFRAB Status
  introTitle: "AFRAB System Status"
  introMessage: "This page shows the real-time status of our services"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
